In [ ]:
# Q1. Create one variable containing following type of data:
# (i) string
# (ii) list
# (iii) float
# (iv) tuple

a = "srujan"
b = ["srujan"]
c = 1.57
d = ("srujan",)
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'str'>
<class 'list'>
<class 'float'>
<class 'tuple'>

In [ ]:
# Q2. Given are some following variables containing data:
var1 = ''
var2 = '[ DS , ML , Python]'
var3 = ['DS' , 'ML' , 'Python' ]
var4 = 1
# What will be the data type of the above given variable.

# Answers :
# (i) string
# (ii) string
# (iii) List
# (iv) int

print(type(var1))
print(type(var2))
print(type(var3))
print(type(var4))

<class 'str'>
<class 'str'>
<class 'list'>
<class 'int'>

In [ ]:
# # Q3. Explain the use of the following operators using an example:
# # (i) /
# # (ii) %
# # (iii) //
# # (iv) **

# Answers :
# 1. / is used for dividing
# 2. % is used for finding the remainder
# 3. // is used for floor divison
# 4. ** is used to find the exponent of a given no.

In [ ]:
# Q4. Create a list of length 10 of your choice containing multiple types of data. Using for loop print the
# element and its data type.

# A4.
l = [1,'a',2.4,(5,),[6],2,2,2,2,2]
for item in l:
  print(type(item))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'tuple'>
<class 'list'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

In [5]:
# Q5. Using a while loop, verify if the number A is purely divisible by number B and if so then how many
# times it can be divisible.

A = int(input('Enter the value of A:'))
B = int(input('Enter the value of B:'))
if A%B==0:
  print(f"{A} is purely divisible by {B}")
  x = A/B
  x = int(x)
  print(f'{A} is purely divisible by {B} by {x} times')
else :
  print(f'{A} is not purely divisible by {B}')

Enter the value of A:15
Enter the value of B:5
15 is purely divisible by 5
15 is purely divisible by 5 by 3 times

In [10]:
# Q6. Create a list containing 25 int type data. Using for loop and if-else condition print if the element is
# divisible by 3 or not.

import numpy as np
l = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
j = np.arange(35)
for item in l:
  if item%3==0:
    print(f"{item} is divisible by 3")
  else:
    print(f'{item} is not divisible by 3')

1 is not divisible by 3
2 is not divisible by 3
3 is divisible by 3
4 is not divisible by 3
5 is not divisible by 3
6 is divisible by 3
7 is not divisible by 3
8 is not divisible by 3
9 is divisible by 3
10 is not divisible by 3
11 is not divisible by 3
12 is divisible by 3
13 is not divisible by 3
14 is not divisible by 3
15 is divisible by 3
16 is not divisible by 3
17 is not divisible by 3
18 is divisible by 3
19 is not divisible by 3
20 is not divisible by 3
21 is divisible by 3
22 is not divisible by 3
23 is not divisible by 3
24 is divisible by 3
25 is not divisible by 3

Q7. What do you understand about mutable and immutable data types? Give examples for both showing
this property.

A7. mutable means the value can be changed. immutable means the value cannot be changed.
Ex mutable : list
Ex immutalbe : tuple